# targets:
#   $default:
#     builders:
#       freezed:
#         options:
#           build_extensions:
          # 'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
            # 'lib/data_classes/{{file}}.dart': 'lib/data_classes/generated/{{file}}.freezed.dart'
      # source_gen|combining_builder:
      #   generate_for:
      #     - lib/data_classes/**/*.freezed.dart  # Focus on only Freezed files within data_classes
      #   options:
      #     build_extensions:
      #       'lib/data_classes/{{file}}.freezed.dart': 'lib/data_classes/generated/{{file}}.g.dart'  # Specific naming convention
      # freezed:
      #   options:
      #     build_extensions:
      #       'lib/data_classes/{{file}}.freezed.dart': 'lib/data_classes/generated/{{file}}.g.dart'  # Matched with source_gen for consistency
      #     field_rename: snake
      #     explicit_to_json: true
      # json_serializable:
      #   options:
      #     field_rename: snake
      #     explicit_to_json: true


# targets:
#   $default:
#     builders:
#       source_gen|combining_builder:
#         generate_for:
#           - lib/data_classes/**/*.freezed.dart
#         # options:
#         #   build_extensions:
#         #     # I want this line to "work":
#         #     # '^lib/**/{{}}.dart': 'lib/generated/model/{{}}.g.dart'
#         #     'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
#       freezed:
#         options:
#           build_extensions:
#             # I want this line to "work":
#             # '^lib/**/{{}}.dart': 'lib/generated/model/{{}}.freezed.dart'
#             'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/data_classes/generated/{{file}}.freezed.dart'
#           field_rename: snake
#           explicit_to_json: true
#       # json_serializable:
#       #   options:
#       #     field_rename: snake
#       #     explicit_to_json: true